
# Num objetos, detalles extra de ser necesarios
# Descripcion categoria 1
# Descripcion categoria 2

TASKS_SVRT = [
    # 2 Objects, not in contact and not inside one another.
    # C1: Objects are equal up to translation.
    # C2: Objects are not equal.
    ["task_svrt_1", task_svrt_1],
    # 2 Objects, one always inside the other.
    # C1: Inner object is near the center of the bigger one.
    # C2: ...
    ["task_svrt_2", task_svrt_2],
    # 4 Objects, similar size.
    # C1: Only 3 objects are in contact.
    # C2: 2 pairs of objects in contact.
    ["task_svrt_3", task_svrt_3],
    # 2 Objects.
    # C1: One object inside the other.
    # C2: ...
    ["task_svrt_4", task_svrt_4],
    # 4 Objects.
    # C1: 2 pairs of identical objects.
    # C2: 4 different objects.
    ["task_svrt_5", task_svrt_5],
    # 4 Objects, 2 identical pairs.
    # C1: Distance between the two identical objects is the same for both pairs.
    # C2: ...
    ["task_svrt_6", task_svrt_6],
    # 6 Objects.
    # C1: objects can be organized in three groups, each consisting of two identical objects.
    # C2: they can be organized into two groups of three identical objects.
    ["task_svrt_7", task_svrt_7],
    # 2 Objects, one larger than the other.
    # C1: small object is inside the large one and is identical to it.
    # C2: small object is either oustide or inside the large one, but is never identical to it.
    ["task_svrt_8", task_svrt_8],
    # 3 Objects, all identical and aligned but one is larger.
    # C1: Larger object is in the middle of the two smaller ones.
    # C2: Larger object is not in the middle of the two smaller ones.
    ["task_svrt_9", task_svrt_9],
    # x Objects, ...
    # C1: ...
    # C2: ...
    ["task_svrt_10", task_svrt_10],
    # 2 Objects, different sizes.
    # C1: The objects make tangential contact.
    # C2: The objects do not make any kind of contact and can't be inside each other.
    ["task_svrt_11", task_svrt_11],
    # x Objects, ...
    # C1: ...
    # C2: ...
    ["task_svrt_12", task_svrt_12],
    # x Objects, ...
    # C1: ...
    # C2: ...
    ["task_svrt_13", task_svrt_13],
    # 3 Objects, all identical.
    # C1: The object's centers are aligned.
    # C2: The centers are not aligned.
    ["task_svrt_14", task_svrt_14],
    # x Objects, ...
    # C1: ...
    # C2: ...
    ["task_svrt_15", task_svrt_15],
    # x Objects, ...
    # C1: ...
    # C2: ...
    ["task_svrt_16", task_svrt_16],
    # x Objects, ...
    # C1: ...
    # C2: ...
    ["task_svrt_17", task_svrt_17],
    # x Objects, ...
    # C1: ...
    # C2: ...
    ["task_svrt_18", task_svrt_18],
    # x Objects, ...
    # C1: ...
    # C2: ...
    ["task_svrt_19", task_svrt_19],
    # x Objects, ...
    # C1: ...
    # C2: ...
    ["task_svrt_20", task_svrt_20],
    # x Objects, ...
    # C1: ...
    # C2: ...
    ["task_svrt_21", task_svrt_21],
    # 3 Objects, all aligned
    # C1: The objects are identical.
    # C2: The objects are not identical.
    ["task_svrt_22", task_svrt_22],
    # x Objects, ...
    # C1: ...
    # C2: ...
    ["task_svrt_23", task_svrt_23],
    # x Objects, ...
    # C1: ...
    # C2: ...
    ["task_MTS", task_MTS],
    # x Objects, ...
    # C1: ...
    # C2: ...
    ["task_SD", task_SD],
    # x Objects, ...
    # C1: ...
    # C2: ...
    ["task_SOSD", task_SOSD],
    # x Objects, ...
    # C1: ...
    # C2: ...
    ["task_RMTS", task_RMTS]
]
